<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Adicionar Fotos</h2>
        <div class="fh5co-spacer fh5co-spacer-sm"></div>

        <form enctype="multipart/form-data" action="/add/photo" method="post">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Título</label>
                        <input type="text" name="title_photo" class="form-control" placeholder="Informe uma breve descrição" required>
                    </div>
                    <div class="form-group">
                        <label>Foto</label>
                        <input type="file" name="file_photo" class="form-control" accept="image/png, image/jpeg" required>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" name="submit_photo" class="btn btn-primary" value="Enviar Foto">
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>