<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Listar Fotos</h2>
        <div class="panel panel-default panel-table">
            <div class="panel-heading">
                <div class="row">
                    <div class="col col-xs-6">
                        <h3 class="panel-title">Painel de Fotos</h3>
                    </div>
                    <div class="col col-xs-6 text-right">
                        <a href="/add" class="btn btn-primary btn-create" role="button">Adicionar Fotos</a>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                    <thead>
                    <tr>
                        <th style="width:10%"><em class="icon-cog"></em></th>
                        <th class="hidden-xs">ID</th>
                        <th>Título</th>
                        <th>Arquivo</th>
                        <th>Criação</th>
                        <th>Modificação</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($this->view->photos) && isset($this->view->photos)): ?>
                        <?php foreach ($this->view->photos as $photo):?>
                            <tr>
                                <td align="center">
                                    <p class="fh5co-social-icons">
                                        <a href="/edit?id=<?= $photo['id'] ?>"><i class="icon-edit"></i></a>
                                        <a href="javascript:void(0)" class="delete" data-id="<?= $photo['id'] ?>"><i class="icon-trash"></i></a>
                                    </p>
                                </td>
                                <td class="hidden-xs"><?= $photo['id'] ?></td>
                                <td><?= $photo['title'] ?></td>
                                <td><img src="images/<?= $photo['name'] ?>" alt="<?= $photo['title'] ?>" width="100" height="100"></td>
                                <td><?= $photo['created'] ?></td>
                                <td><?= $photo['modified'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" align="center">Nenhum registro encontrado</td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>

            </div>
<!--            <div class="panel-footer">-->
<!--                <div class="row">-->
<!--                    <div class="col col-xs-4">Page 1 of 5-->
<!--                    </div>-->
<!--                    <div class="col col-xs-8">-->
<!--                        <ul class="pagination hidden-xs pull-right">-->
<!--                            <li><a href="#">1</a></li>-->
<!--                            <li><a href="#">2</a></li>-->
<!--                            <li><a href="#">3</a></li>-->
<!--                            <li><a href="#">4</a></li>-->
<!--                            <li><a href="#">5</a></li>-->
<!--                        </ul>-->
<!--                        <ul class="pagination visible-xs pull-right">-->
<!--                            <li><a href="#">«</a></li>-->
<!--                            <li><a href="#">»</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
        </div>
    </div>
</div>
